### ISSUE TITLE
pages aren't self-contained

### ISSUE THREAD

**Issue by YtvwlD** [guillaumebriday/traefik-custom-error-pages#4]
Maybe I'm doing something wrong or didn't fully understand the intention of this repository, but I wasn't really successful setting this up as custom error pages for Traefik.

I did add the following labels to all my applications:

```
- traefik.frontend.errors.network.backend=error-app
- traefik.frontend.errors.network.status=401,403,404,429,500,503
- traefik.frontend.errors.network.query=/{status}.html
```

I added this docker image as `error-app` backend.

Now, all responses with one of these error codes are being correctly replaced with the appropriate error page. But the page is mostly empty, because it requests an external CSS and SVG - which also 404 and get replaced with the HTML error page.

**Comment by romancin** [comment]
The same for me. Are we doing something wrong?

**Comment by linusg** [comment]
I found a solution for this I'd like to share, but it's not the most elegant one - decide for yourself if it's worth doing. I'm using Traefik v2.

Let's assume the following configuration:

**`docker-compose.yml`**

```yml
version: '3'

services:
  traefik:
    ...

  error-pages:
    image: guillaumebriday/traefik-custom-error-pages
    depends_on:
      - traefik
    labels:
      - "traefik.http.routers.error-pages.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.error-pages.entrypoints=web"
      - "traefik.http.routers.error-pages.priority=1"

  app:
    image: ...
    depends_on:
      - traefik
      - error-pages
    labels:
      - "traefik.http.routers.app.rule=Host(`example.com`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.routers.app.middlewares=error-pages@file"
      - "traefik.http.routers.app.priority=10"
```

**Traefik dynamic configuration (file provider)**

```yml
http:
  middlewares:

    error-pages:
      errors:
        status:
          - "400-599"
        service: "error-pages-<docker-compose-project-name>@docker"
        query: "/{status}.html"
```

We want to show the custom error pages for:

- Any subdomain without specified Traefik router (``HostRegexp(`{host:.+}`)`` with low priority)
- Any request that returns a status code between 400 and 599

The main issue here is how the assets used by the `guillaumebriday/traefik-custom-error-pages` pages are referenced - as relative URLs:

https://github.com/guillaumebriday/traefik-custom-error-pages/blob/4df490efc5c50a244c9ac8efed3b750c3c32dc10/_layouts/default.html#L33

Now we visit `http://example.com/does-not-exist`, Traefik catches the 404 error code and serves the `404.html` error page instead. The browser tries to fetch the referenced images and CSS as `http://example.com/assets/404.svg` and `http://example.com/assets/application.css`, which both return 404 as well, so their responses both contain _**the HTML of the status page again**_ (you can check this in the browser's devtools). Doesn't work like this. :confused:

Now here's the fix - we need to tell Traefik to always route the error page asset requests to the `error-pages` service.

We can do so using the `redirectRegex` middleware. We just have to replace the domain of the failed request with something that's being routed to the `error-pages` service - which is using a catch-all regex in our case, so anything not used by other routers will do:

```diff
http:
  middlewares:

    error-pages:
      errors:
        status:
          - "400-599"
        service: "error-pages-<docker-compose-project-name>@docker"
        query: "/{status}.html"

+   error-pages-assets:
+     redirectRegex:
+       regex: "^https?://.+/(assets/application\\.css|assets/[4|5]\\d\\d\\.svg)"
+       replacement: "http://_errors.example.com/${1}"
```

Now update `docker-compose.yml` to use this new middleware:

```diff
version: '3'

services:
  traefik:
    ...

  error-pages:
    image: guillaumebriday/traefik-custom-error-pages
    depends_on:
      - traefik
    labels:
      - "traefik.http.routers.error-pages.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.error-pages.entrypoints=web"
+     - "traefik.http.routers.error-pages.middlewares=error-pages@file,error-pages-assets@file"
      - "traefik.http.routers.error-pages.priority=1"

  app:
    image: ...
    depends_on:
      - traefik
      - error-pages
    labels:
      - "traefik.http.routers.app.rule=Host(`example.com`)"
      - "traefik.http.routers.app.entrypoints=web"
-     - "traefik.http.routers.app.middlewares=error-pages@file"
+     - "traefik.http.routers.app.middlewares=error-pages@file,error-pages-assets@file"
      - "traefik.http.routers.app.priority=10"
```

Of course there's one issue - even legitimate requests to `assets/application.css` will always be redirected to `http://_errors.example.com/assets/application.css`. This risk of false-positives could be reduced if @guillaumebriday would rename the `assets` directory to for example `error-page-assets`.

Again, this isn't a clean solution, but I'm afraid it's the best one available.

Sorry, I think I'm making this sound more complicated that it actually is. Hope it helps!
