### ISSUE TITLE
Inline assets?

### ISSUE THREAD

**Issue by fauzanelka** [guillaumebriday/traefik-custom-error-pages#7]
Hello, thanks for making such beautiful error page.

So, I'm trying to achieve a simple failover in traefik 2.0.
I'm using your image as a service and a middleware for error pages in traefik.
However, there's something bothering me. Because all assets is external it could'nt fetch the assets when error happens. (404 return page). I could fix this by declaring new router and pathprefix but it could lead to another problem. So I'm here to ask you, could you make all assets inline?

Here's my configuration for demonstrating traefik simple failover.

**docker-compose.yml:**
```
version: "3.7"
services:
  traefik:
    image: traefik:2.2
    container_name: traefik
    volumes:
      - type: bind
        source: ./traefik/traefik.yml
        target: /etc/traefik/traefik.yml
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: ./logs
        target: /var/log/traefik
    ports:
      - 80:80
    networks:
      - traefik
  local_service:
    image: emilevauge/whoami
    container_name: local_service
    networks:
      - traefik
  failover:
    image: guillaumebriday/traefik-custom-error-pages
    container_name: failover
    networks:
      - traefik
networks:
  traefik:
    external: true
```

**traefik.yml**
```
log:
  level: ERROR
  filePath: /var/log/traefik/error.log

accessLog:
  filePath: /var/log/traefik/access.log

entryPoints:
  web:
    address: ":80"

http:
  middlewares:
    errorpage:
      errors:
        status:
          - "400-599"
        service: failover
        query: "/{status}.html"
  routers:
    localAssets: #This is the fix
      entryPoints:
        - web
      rule: Host(`default.test`) && PathPrefix(`/assets`)
      service: failover
    local:
      entryPoints:
        - web
      middlewares:
        - errorpage
      rule: Host(`default.test`)
      service: local
    failover:
      entryPoints:
        - web
      priority: 1
      rule: HostRegexp(`{catchall:.*}`)
      service: failover
  services:
    local:
      loadBalancer: #This will remove server when healthcheck fail, returning 503 service unavailable, then it handled by errorpage middleware
        healthCheck:
          path: /
          scheme: http
          interval: 1s
          timeout: 3s
        servers:
          - url: http://local_service
    failover:
      loadBalancer:
        servers:
          - url: http://failover

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true
```
